---

- name: Set up /etc/hostname.
  template:
    src: "{{item}}"
    dest: /etc/hostname
    owner: root
    group: "{{ hosts_file_group }}"
    mode: 0644
  with_first_found:
    - files:
        - hostname.j2
      paths:
        - ../templates

