---

- name: Set up /etc/hosts.
  template:
    src: "{{ item }}"
    dest: /etc/hosts
    owner: root
    group:  "{{ hosts_file_group }}"
    mode: 0644
  with_first_found:
    - files:
        - hosts.j2
      paths:
        - ../templates

- name: Reboot the host
  include_role:
    name: common
    tasks_from: reboot
  when: ansible_distribution == "Ubuntu"
